/**
 * 
 */
package com.shinylana.ui.composites;

import java.util.List;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

/**
 * @author phillippohl
 * @version 0.1
 */
public class MarketComposite extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Table table_1;
	private int rowCounter;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MarketComposite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		setupMarketTable();
	}
	
	private void setupMarketTable() {
		table_1.addContainerProperty("Market", String.class, "");
		table_1.addContainerProperty("Market Volume", Double.class, 0);
		table_1.addContainerProperty("Volume Change", Double.class, 0);
	}
	
	public Table getTable() {
		return table_1;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// table_1
		table_1 = new Table();
		table_1.setImmediate(false);
		table_1.setWidth("100.0%");
		table_1.setHeight("100.0%");
		mainLayout.addComponent(table_1);
		mainLayout.setExpandRatio(table_1, 1.0f);
		
		return mainLayout;
	}
	
	public void addTableRow(List newRecord) {
		rowCounter = table_1.size();
		if (rowCounter == 0) {
			rowCounter = 1;
		}
		table_1.addItem(new Object[] {newRecord.get(1), newRecord.get(2), newRecord.get(3)}, new Integer(rowCounter));
	}
}