package com.shinylana.ui.composites;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;

public class RegisterComposite extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private TextField textField_1;
	@AutoGenerated
	private PasswordField passwordField_1;
	@AutoGenerated
	private PasswordField passwordField_2;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private Button button_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public RegisterComposite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	public Button getRegisterButton() {	
		return button_1;
	}
	
	public TextField getUsername() {	
		return textField_1;
	}
	
	public PasswordField getPassword() {
		return passwordField_1;
	}
	
	public PasswordField getPasswordRepeat() {
		return passwordField_2;
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Login");
		button_1.setImmediate(true);
		button_1.setWidth("100px");
		button_1.setHeight("-1px");
		mainLayout.addComponent(button_1, "top:380.0px;left:220.0px;");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Username");
		mainLayout.addComponent(label_1, "top:202.0px;left:200.0px;");
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Password");
		mainLayout.addComponent(label_2, "top:260.0px;left:200.0px;");
		
		// passwordField_1
		passwordField_1 = new PasswordField();
		passwordField_1.setImmediate(false);
		passwordField_1.setWidth("-1px");
		passwordField_1.setHeight("-1px");
		mainLayout.addComponent(passwordField_1, "top:278.0px;left:200.0px;");
		
		// textField_1
		textField_1 = new TextField();
		textField_1.setImmediate(false);
		textField_1.setWidth("-1px");
		textField_1.setHeight("-1px");
		mainLayout.addComponent(textField_1, "top:220.0px;left:200.0px;");
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("Repeat password");
		mainLayout.addComponent(label_3, "top:322.0px;left:200.0px;");
		
		// passwordField_2
		passwordField_2 = new PasswordField();
		passwordField_2.setImmediate(false);
		passwordField_2.setWidth("-1px");
		passwordField_2.setHeight("-1px");
		mainLayout.addComponent(passwordField_2, "top:340.0px;left:200.0px;");
		
		return mainLayout;
	}
}